trigger:
- main #change master to something else if master is not your main branch
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'edme-sonarqube'
    scannerMode: 'MSBuild'
    projectKey: 'EDME_EDMEAzureDataFactory_AZFGMQ2ISZV5KyjDxaHQ'
    projectName: 'EDME'
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'
 
- task: Npm@1
  inputs:
    command: 'install'
    verbose: true
  displayName: 'Install npm package'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build validate $(Build.Repository.LocalPath) /subscriptions/f2330f9f-3a8b-498c-a2d6-476e4f263349/resourceGroups/afi-edme-rg/providers/Microsoft.DataFactory/factories/afi-edme-dev-df'
  displayName: 'Validate'
 
# Validate and then generate the ARM template into the destination folder. Same as clicking "Publish" from UX
# The ARM template generated is not published to the ‘Live’ version of the factory. Deployment should be done using a release pipeline.
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build export $(Build.Repository.LocalPath) /subscriptions/f2330f9f-3a8b-498c-a2d6-476e4f263349/resourceGroups/afi-edme-rg/providers/Microsoft.DataFactory/factories/afi-edme-dev-df "ArmTemplate"'
  displayName: 'Validate and Generate ARM template'
 
# Publish the Artifact to be used as a source for a release pipeline
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.Repository.LocalPath)/ArmTemplate'
    artifact: 'ArmTemplates'
    publishLocation: 'pipeline'